"""initial catalog schema

Revision ID: ba1c8e96da0d
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = 'ba1c8e96da0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """初始化 15 张业务表；先启用 pg_trgm，后续生成的 GIN 中文检索索引依赖它。以下建表 DDL 由 Alembic 根据 models.py 自动生成。"""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('identity_key', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('dynasty', sa.String(length=16), nullable=False),
    sa.Column('birth_year_min', sa.Integer(), nullable=True),
    sa.Column('birth_year_max', sa.Integer(), nullable=True),
    sa.Column('death_year_min', sa.Integer(), nullable=True),
    sa.Column('death_year_max', sa.Integer(), nullable=True),
    sa.Column('identity_status', sa.String(length=20), server_default='unverified', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key')
    )
    op.create_table('sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('author_attributions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_index', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Text(), nullable=True),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('raw_biography', sa.Text(), nullable=True),
    sa.Column('raw_short_biography', sa.Text(), nullable=True),
    sa.Column('match_status', sa.String(length=20), server_default='unverified', nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_path', 'source_index')
    )
    op.create_index('ix_author_attributions_name', 'author_attributions', ['original_name'], unique=False)
    op.create_table('author_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('date_precision', sa.String(length=24), nullable=False),
    sa.Column('event_label', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=24), server_default='pending', nullable=False),
    sa.CheckConstraint('year_start <= year_end'),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('external_key', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('language_tag', sa.String(length=40), nullable=True),
    sa.Column('origin_type', sa.String(length=32), server_default='imported', nullable=False),
    sa.Column('creator_name', sa.Text(), nullable=True),
    sa.Column('generation_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_status', sa.String(length=24), server_default='staged', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_key')
    )
    op.create_table('works',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('identity_key', sa.Text(), nullable=False),
    sa.Column('genre', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('original_author_name', sa.Text(), nullable=False),
    sa.Column('identity_status', sa.String(length=24), server_default='normal', nullable=False),
    sa.CheckConstraint("genre IN ('tang_poem','song_poem','song_ci')"),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key')
    )
    op.create_index('ix_works_author_genre', 'works', ['author_id', 'genre'], unique=False)
    op.create_table('author_biographies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id')
    )
    op.create_table('rights_reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('permitted_scope', sa.Text(), nullable=True),
    sa.Column('evidence_uri', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_hash', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_current_rights_review', 'rights_reviews', ['material_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('work_dates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('date_precision', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.String(length=24), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('is_preferred', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('year_start <= year_end'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_work_dates_timeline', 'work_dates', ['year_start', 'year_end'], unique=False)
    op.create_table('work_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_index', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('rhythmic', sa.Text(), nullable=True),
    sa.Column('prologue', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id'),
    sa.UniqueConstraint('work_id', 'version_number')
    )
    op.create_index('ix_work_version_search_trgm', 'work_versions', ['search_text'], unique=False, postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.create_index('ix_work_version_source_locator', 'work_versions', ['source_path', 'source_index'], unique=False)
    op.create_index('uq_current_work_version', 'work_versions', ['work_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('pinyin_sets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_version_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('romanization', sa.String(length=40), server_default='hanyu-pinyin', nullable=False),
    sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alignment_sha256', sa.String(length=64), nullable=False),
    sa.Column('review_status', sa.String(length=24), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['work_version_id'], ['work_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id')
    )
    op.create_table('translation_editions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_version_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('language_tag', sa.String(length=40), nullable=False),
    sa.Column('translator_name', sa.Text(), nullable=True),
    sa.Column('alignment_mode', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['work_version_id'], ['work_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id')
    )
    op.create_table('work_paragraphs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_version_id', sa.BigInteger(), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['work_version_id'], ['work_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_version_id', 'paragraph_index')
    )
    op.create_table('commentaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_version_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('work_paragraph_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('commentator_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['work_paragraph_id'], ['work_paragraphs.id'], ),
    sa.ForeignKeyConstraint(['work_version_id'], ['work_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id')
    )
    op.create_table('translation_blocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('edition_id', sa.BigInteger(), nullable=False),
    sa.Column('work_paragraph_id', sa.BigInteger(), nullable=True),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['translation_editions.id'], ),
    sa.ForeignKeyConstraint(['work_paragraph_id'], ['work_paragraphs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'block_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation_blocks')
    op.drop_table('commentaries')
    op.drop_table('work_paragraphs')
    op.drop_table('translation_editions')
    op.drop_table('pinyin_sets')
    op.drop_index('uq_current_work_version', table_name='work_versions', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_work_version_source_locator', table_name='work_versions')
    op.drop_index('ix_work_version_search_trgm', table_name='work_versions', postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.drop_table('work_versions')
    op.drop_index('ix_work_dates_timeline', table_name='work_dates')
    op.drop_table('work_dates')
    op.drop_index('uq_current_rights_review', table_name='rights_reviews', postgresql_where=sa.text('is_current'))
    op.drop_table('rights_reviews')
    op.drop_table('author_biographies')
    op.drop_index('ix_works_author_genre', table_name='works')
    op.drop_table('works')
    op.drop_table('materials')
    op.drop_table('author_events')
    op.drop_index('ix_author_attributions_name', table_name='author_attributions')
    op.drop_table('author_attributions')
    op.drop_table('sources')
    op.drop_table('authors')
    # ### end Alembic commands ###
